# Nginx main configuration file

worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Including custom virtual host configuration
    include /etc/nginx/conf.d/*.conf;

    # Logging
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Gzip configuration (optional)
    gzip on;
    gzip_disable "msie6";
}
