server {
    listen 80;
    server_name localhost;

    # Document root for the website
    root /var/www/project;
    index index.html index.hml;

    # Serve the index page
    location / {
        try_files $uri $uri/ =404;
    }

    # Error page handling (optional)
    error_page 404 /404.html;
    location = /40x.html {
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
    }
}
