name: Nginx Web Server Deployment

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  Staging_deploy:
    if: github.repository == 'devocon-org/git-action-nginx-docker'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Staging
        run: |
          echo "Deploying to Staging environment..."
          # Add your deployment script/command here, such as:
          # ssh user@Staging-server 'deploy command'

  nginx_build_deploy:
    needs: Staging_deploy
    runs-on: [self-hosted, linux, office-laptop]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop and remove containers with 'nginx' in the name
        run: |
          docker stop $(docker ps -a -q -f "name=nginx") || true
          docker rm $(docker ps -a -q -f "name=nginx") || true

      - name: Build Docker image
        run: |
          docker build -t nginx/ken .

      - name: Run Docker container with mounted volumes
        run: |
          docker run -d -p 8080:80 --name uat-nginx-server -v $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf -v $PWD/src:/usr/share/nginx/html --log-driver=json-file nginx/ken

      - name: Restart Docker container if changes or new files in nginx/ or src/
        run: |
          git diff --exit-code --quiet nginx/ src/ || {
            echo "Changes or new files detected in nginx/ or src/. Restarting container..."
            docker restart uat-nginx-server
          }

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Tag Docker image with a specific version or commit hash
      - name: Tag Docker image
        run: |
          # Use commit SHA or version tag, such as "v1.0" or "latest"
          IMAGE_TAG="${GITHUB_SHA}"  # Use Git commit SHA as tag
          docker tag nginx/ken ${{ secrets.DOCKER_USERNAME }}/nginx-ken:${IMAGE_TAG}
          docker tag nginx/ken ${{ secrets.DOCKER_USERNAME }}/nginx-ken:latest  # Optionally tag as "latest"

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          IMAGE_TAG="${GITHUB_SHA}"
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-ken:${IMAGE_TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-ken:latest  # Push the "latest" tag
